// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart' ;
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJNQz_1sI8cLU0XQJumDQtg_6U5sd6MPU',
    appId: '1:89002940560:web:72e75277c3cbca2f9ae015',
    messagingSenderId: '89002940560',
    projectId: 'focus-timer-app-4a5c4',
    authDomain: 'focus-timer-app-4a5c4.firebaseapp.com',
    storageBucket: 'focus-timer-app-4a5c4.firebasestorage.app',
    measurementId: 'G-03BVPM7Q0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjnUdJVB5xOocnB7RMIK3ygioIZHU1eXc',
    appId: '1:89002940560:android:1e99a8d3a212b57b9ae015',
    messagingSenderId: '89002940560',
    projectId: 'focus-timer-app-4a5c4',
    storageBucket: 'focus-timer-app-4a5c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6f2S9PuklwQU5vqozXGQlGV-pvPU1BI4',
    appId: '1:89002940560:ios:f2f0d3dc3e6e5c7a9ae015',
    messagingSenderId: '89002940560',
    projectId: 'focus-timer-app-4a5c4',
    storageBucket: 'focus-timer-app-4a5c4.firebasestorage.app',
    iosBundleId: 'com.example.focusflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6f2S9PuklwQU5vqozXGQlGV-pvPU1BI4',
    appId: '1:89002940560:ios:f2f0d3dc3e6e5c7a9ae015',
    messagingSenderId: '89002940560',
    projectId: 'focus-timer-app-4a5c4',
    storageBucket: 'focus-timer-app-4a5c4.firebasestorage.app',
    iosBundleId: 'com.example.focusflow',
  );
}
